export const content = {
  ru: {
    metaTitle: "Games Watchtower — прозрачная Web3-игровая экосистема",
    metaDescription:
      "4 игры на Solana. 1 операционная система. 100 Ecosystem Share NFT = 25% чистой прибыли студии. Прозрачная математика и план квартальных выплат USDC.",
    nav: ["Экосистема", "Watchtower", "Математика", "Roadmap"],
    navCta: "Стать инвестором",
    menu: "Открыть меню",
    close: "Закрыть",
    skip: "Перейти к содержимому",
    heroEyebrow: "GAMES WATCHTOWER × ECOSYSTEM SHARE",
    heroTitle: ["Прозрачная Web3-", "игровая экосистема."],
    heroAccent: "Никаких скрытых цифр.",
    heroSub: "4 игры на Solana. 1 операционная система.",
    heroBody:
      "100 NFT «Ecosystem Share» — вместе 25% чистой прибыли студии. Тот же дашборд, что у основателя. Ежеквартальные выплаты USDC, которые можно проверить on-chain.",
    heroPrimary: "Купить долю",
    heroSecondary: "Смотреть дашборд",
    demo: "демо",
    plannedPresale: "Планируемый presale",
    heroNote: "Смарт-контракт выплат — в планах. Продажа ещё не открыта.",
    onSolana: "Построено на Solana",
    transparent: "Прозрачность по дизайну",
    dashboard: {
      title: "Обзор экосистемы",
      welcome: "Вся студия. В одном окне.",
      tabs: ["Обзор", "Воронки", "Инвесторам", "Трафик"],
      ecosystem: "Экосистема",
      quality: "Качество данных",
      events: "Поток событий",
      eventNote: "Иллюстрация, не фактическая активность",
      live: "READ-ONLY",
      games: "Игры",
      sources: "Источники",
      profit: "Чистая прибыль",
      unavailable: "Нет live-данных",
      integration: "Интеграция в работе",
      coverage: "Покрытие данных",
      report: "Квартальный отчёт",
      wallet: "Кошелёк холдера",
      snapshots: "Снапшоты и выплаты",
      planned: "В планах",
      channels: "Каналы привлечения",
      bot: "Боты и люди учитываются отдельно",
      funnelStages: ["Источник", "Визит", "Онбординг", "Игра"],
      funnelNote: "Схема воронки • конверсии недоступны",
      investorNote: "Персональный доступ появится после запуска",
      trafficNote: "Исторические данные подключаются",
      os: "Операционная система студии",
      preview: "Интерактивный макет",
      noLive: "Live-данные не подключены",
      expand: "Развернуть демо",
      collapse: "Свернуть демо",
    },
    data: {
      quality: {
        complete: "COMPLETE",
        partial: "PARTIAL",
        unavailable: "UNAVAILABLE",
      },
      qualityTitle: "Качество данных",
      qualityNote:
        "Словарь хаба: complete — значение подтверждено, partial — часть полей отсутствует, unavailable — данных нет.",
      source: "Источник",
      asOf: "На момент",
      formula: "Формула",
      timezone: "UTC",
      demo: "DEMO DATA",
      demoNote:
        "Значения получены из mock-режима хаба и не являются фактическими.",
      loading: "Читаем данные из хаба…",
      retry: "Повторить запрос",
      showSource: "Показать источник",
      updated: "Данные обновлены",
      notUpdated: "Живые данные ещё не получены",
      readOnly: "READ-ONLY",
      unavailableTitle: "Данные недоступны",
      mockBanner:
        "Хаб отвечает в режиме mock-read-model. Все числа на странице — демонстрационные, а не фактические.",
      reasons: {
        endpoint_not_deployed:
          "Эндпоинт отсутствует в текущей сборке хаба. Данные не подставляются.",
        timeout: "Хаб не ответил за отведённое время. Старые значения не подставляем.",
        network_error: "Запрос к хабу не выполнен: сеть недоступна.",
        http_error: "Хаб ответил ошибкой.",
        not_json: "Ответ не является JSON — данные не приняты.",
        unknown_endpoint: "Неизвестный эндпоинт.",
      },
    },
    hub: {
      label: "06 / СОСТОЯНИЕ ЭКОСИСТЕМЫ",
      title: "Что подключено, а что нет.",
      body: "Экран состояния читает один эндпоинт хаба и показывает только то, что он вернул. Если хаб молчит, экран говорит об этом прямо и не назначает уровни сам.",
      endpoint: "Эндпоинт",
      navLabel: "Состояние",
      games: "Игры",
      apps: "Сервисы",
      stage: "Стадия",
      level: "Уровень",
      connected: "Подключено",
      disconnected: "Не подключено",
      why: "Причина",
      checkedAt: "Проверено",
      levelsTitle: "Уровни зрелости L0–L4",
      levelsNote:
        "Словарь уровней публикует хаб. Лендинг не присваивает уровни самостоятельно.",
      levels: [
        ["L0", "Идея: репозиторий и описание"],
        ["L1", "Макет: интерфейсы на mock-данных"],
        ["L2", "Интеграция: адаптеры настроены, события поступают"],
        ["L3", "Live-данные: подтверждённый поток, отчёты сходятся"],
        ["L4", "Автономность: алерты и регулярная отчётность"],
      ],
      appsList: [
        ["Watchtower API", "read-only аналитика"],
        ["TalkChart", "движок привлечения (interlock i-09)"],
        ["Consent & opt-out", "журнал согласий (interlock i-02)"],
        ["Snapshot publisher", "публикация выплат после подтверждения"],
      ],
      appsNote:
        "Список сервисов — контракт лендинга с хабом, а не отчёт о готовности.",
      pendingTitle: "Хаб пока не отдаёт этот эндпоинт",
      pendingBody:
        "Эндпоинт отсутствует в текущей сборке хаба, поэтому уровни L0–L4, подключения и причины недоступности не показываются. Оценок «на глаз» здесь не будет.",
      pendingNext:
        "Как только эндпоинт появится, экран включится без изменений на лендинге.",
      schemaTitle: "Ожидаемая схема ответа",
      schemaNote:
        "Схема зафиксирована здесь, чтобы лендинг и хаб говорили об одном и том же.",
      inventoryTitle: "Что известно прямо сейчас",
      inventoryNote:
        "Готовность адаптеров приходит из GET /api/read-model и показана как есть — с качеством unavailable.",
      adaptersLabel: "Адаптеров настроено",
      retry: "Повторить запрос",
    },
    snapshots: {
      label: "07 / ВЫПЛАТЫ И СНАПШОТЫ",
      navLabel: "Снапшоты",
      title: "Кварталы, которые можно проверить.",
      body: "Каждый подтверждённый квартал приходит из эндпоинта снапшотов хаба и снабжён ссылкой на источник. Неподтверждённых выплат на странице нет.",
      formulaTitle: "Формула",
      formula:
        "выплата на NFT за квартал = (чистая прибыль студии за квартал × 25%) / 100",
      formulaNote:
        "Округление всегда вниз, до цента: выплата не может превысить пул.",
      calendarTitle: "Календарь снапшотов",
      calendar: "Первый рабочий день января, апреля, июля и октября, UTC.",
      calendarNote:
        "Биржевые праздники пока не учтены: правило сдвига даты должен утвердить оператор.",
      holderTitle: "Получатель",
      holder:
        "Актуальный владелец NFT на момент снапшота. Права переходят покупателю со следующего снапшота.",
      zeroTitle: "Квартал без прибыли",
      zero: "Показываем $0 и объясняем причину. Нулевые кварталы не скрываются и не заменяются прогнозом.",
      tableHead: [
        "Квартал",
        "Снапшот",
        "Чистая прибыль",
        "Пул 25%",
        "На NFT",
        "Статус",
        "Источник",
      ],
      statusPublished: "Опубликован",
      statusPending: "Ещё не опубликован",
      statusZero: "Прибыли не было — выплата $0",
      empty: "Хаб пока не отдал ни одного снапшота.",
      emptyWhy:
        "Снапшот публикуется только после подтверждения оператором и фиксации отчёта — это правило, а не задержка.",
      openSource: "Открыть источник",
      nextTitle: "Ближайший снапшот",
      illustrationTitle: "Иллюстрация формулы — не обещание",
      illustration:
        "При чистой прибыли $200,000 за год пул составит $50,000, а выплата на один NFT — $500 за год и $125 за квартал.",
      illustrationNote:
        "Это арифметика формулы, а не прогноз и не гарантия. Квартал без прибыли — выплата $0.",
      trendTitle: "Динамика по снапшотам",
      trendEmpty: "Истории нет, пока не опубликован первый снапшот.",
      trendMinted: "Minted",
      trendBurned: "Burned",
      trendPlayers: "Активные игроки",
    },
    compliance: {
      label: "08 / ГРАНИЦЫ ПРЕДЛОЖЕНИЯ",
      navLabel: "Юридическая часть",
      title: "Что именно покупает инвестор.",
      disclaimerTitle: "Предмет сделки",
      disclaimer:
        "Ecosystem Share NFT — договорное право на долю чистой прибыли студии и read-only доступ к дашборду. Это не доля в капитале компании, не внутриигровой токен и не инвестиционная рекомендация.",
      riskTitle: "Риски, которые нужно принять",
      risks: [
        "Стоимость NFT может упасть до нуля: вторичного рынка может не быть.",
        "Квартал без чистой прибыли означает выплату $0.",
        "Правовая квалификация NFT зависит от юрисдикции и до продажи не подтверждена.",
        "Смарт-контракт выплат ещё не развёрнут и не проходил аудит.",
      ],
      kycTitle: "KYC / AML",
      kyc: "Проверка личности потребуется до покупки. Провайдер KYC/AML ещё не выбран, статус: ожидает решения оператора.",
      kycPending: "Ожидает решения оператора",
      jurisdictionTitle: "Юрисдикция",
      jurisdiction:
        "Список ограниченных юрисдикций публикуется здесь до открытия продажи. Сейчас он пуст, потому что юридическое лицо и его регистрация ещё не определены.",
      jurisdictionPending: "Не опубликован",
      walletTitle: "Лимит на кошелёк",
      wallet: "Лимит задан одним параметром конфигурации и применяется на этапе mint.",
      mintTitle: "Программа mint",
      mint: "Адрес программы не публикуется до подтверждения оператором. Придуманного адреса здесь не будет.",
      mintSupply: "Тираж",
      mintStatus: "Статус",
      mintInProgress: "В работе",
      mintAudit: "Аудит",
      mintMultisig: "Мультиподпись",
      taxTitle: "Налоги",
      tax: "Логика налогообложения выплат зависит от юрисдикции инвестора. Студия не даёт налоговых консультаций.",
      termsTitle: "Условия",
      terms: "Итоговый документ Terms of the Share публикуется до открытия продажи. До этого момента продажа закрыта.",
      reviewNote:
        "Юридическая проверка перед публичным mint — решение оператора, а не автоматический шаг пайплайна.",
      opsTitle: "Эксплуатация и устойчивость",
      opsText:
        "Целевые уровни сервиса: доступность 99.9% и p95 ответа API 300 мс. Публичные отчёты о доступности, резервные копии контента и конфигурации, SBOM и регламент откатa ещё не опубликованы.",
      opsPending: "Регламенты в работе",
    },
    nftLabel: "ОДИН NFT. ДОЛЯ ЭКОСИСТЕМЫ.",
    nftProfit: "чистой прибыли студии",
    nftSupply: "Плановый тираж",
    nftUnits: "NFT",
    nftAccess: "+ доступ к Watchtower",
    stats: [
      "игры в экосистеме",
      "органических каналов",
      "операционная система",
      "NFT = 25% чистой прибыли",
    ],
    statsDetail: [
      "beta / alpha / prototype",
      "SEO, GEO, X, видео, радар, TipLink",
      "с read-only API",
      "один класс · одноразовый дроп",
    ],
    statsNote:
      "Без выдуманных метрик. Интерфейсы на странице — демонстрационные макеты, не live-данные.",
    problemLabel: "01 / ПРОБЛЕМА → РЕШЕНИЕ",
    problemTitle: "Не «поверьте нам».",
    problemAccent: "Проверьте сами.",
    problemBody:
      "Инвесторам в Web3-игры часто нечего проверить. Скриншоты вместо отчётов, обещания вместо цифр. Честные проекты теряются среди тех, кто просто громче обещает.",
    problemEnd:
      "Мы строим другую модель: прозрачность — часть инфраструктуры, а не презентации.",
    problemCards: [
      ["Без закрытых цифр", "Те же данные, что у основателя."],
      ["Без vanity-метрик", "Качество и доступность каждого показателя."],
      ["Без «поверьте на слово»", "План выплат с проверкой on-chain."],
    ],
    watchLabel: "02 / ОПЕРАЦИОННАЯ СИСТЕМА",
    watchTitle: "За каждой цифрой — источник.",
    watchBody:
      "Games Watchtower — ядро студии, открытое инвестору. От игрового события до квартального отчёта — в одной системе.",
    watchFeatures: [
      [
        "Единый слой событий",
        "On-chain и off-chain: дедупликация, курсоры, backfill и обнаружение разрывов.",
      ],
      [
        "Read-only по умолчанию",
        "Аналитика, воронки, алерты и AI-аналитик. Без прямых записей в блокчейн.",
      ],
      [
        "Проверяемая отчётность",
        "Инвесторские отчёты, snapshots и cross-game сегменты.",
      ],
    ],
    watchQuote:
      "«Никаких выдуманных чисел» — принцип системы, а не маркетинговый лозунг.",
    watchQuality: "Каждый показатель имеет quality-статус и confidence:",
    watchCaption:
      "Демонстрационный макет Watchtower. Оригинальные скриншоты ещё не предоставлены.",
    gamesLabel: "03 / ИГРОВАЯ ЭКОСИСТЕМА",
    gamesTitle: "Четыре мира. Одна экосистема.",
    gamesBody:
      "Разные игровые циклы. Общая инфраструктура. Доля в результате всей студии, а не ставка на одну игру.",
    concept: "CONCEPT ART",
    gameData: "Данные: интеграция в работе",
    games: [
      {
        name: "ARES-1",
        sub: "Potato Colony on Solana",
        stage: "beta",
        genre: "FARMING · SOLANA",
        body: "Плантации, ресурс POTATO и награды. Самая зрелая игра — плановый выход в mainnet в Q4 2026.",
      },
      {
        name: "Age of Farming",
        sub: "Расти. Собирай. Создавай.",
        stage: "prototype",
        genre: "FARMING · CRAFTING",
        body: "Поля, урожай и crafting-цепочки. Farming-экономика с балансом источников и расходования ресурсов.",
      },
      {
        name: "Neon Relay",
        sub: "Скорость становится игрой.",
        stage: "prototype",
        genre: "RACING · NEON DM",
        body: "Гонки и Neon DM — быстрая соревновательная петля с наградными расчётами on-chain.",
      },
      {
        name: "GUTTERCAPS",
        sub: "Собирай. Сражайся. Побеждай.",
        stage: "alpha",
        genre: "COLLECTIBLES · PVP",
        body: "Коллекционные предметы, PvP-ставки и токен $CG. On-chain инварианты и антифрод в индексаторе.",
      },
    ],
    gamesNote:
      "Стадии — по реестру студии из брифа. Иллюстрации — концепт-арт, не скриншоты геймплея.",
    trafficLabel: "04 / ДВИЖОК ПРИВЛЕЧЕНИЯ",
    trafficTitle: "Не покупаем аудиторию.",
    trafficAccent: "Находим свою.",
    trafficBody:
      "TalkChart — собственный off-chain движок трафика студии. От первого поиска до первого игрового действия.",
    channels: [
      [
        "SEO / GEO",
        "Программные страницы для Google, Perplexity и ChatGPT Search.",
      ],
      ["X / Twitter", "Дайджесты и интерактивные Solana Blinks прямо в ленте."],
      ["Shorts / TikTok / Reels", "15-секундные вертикальные видео."],
      ["Китовый радар", "Терминал с прогнозами 1ч как retention-петля."],
      ["TipLink", "Вход через Google — без кошелька и сид-фразы."],
    ],
    trafficStats: ["кампаний", "источников", "целевых страниц", "на рекламу"],
    trafficNote:
      "Каналы работают в live-режиме по данным студии. Историческая статистика подключается к Watchtower. Посещаемость здесь не заявляется.",
    offerLabel: "05 / ECOSYSTEM SHARE NFT",
    offerTitle: "100 NFT. 25% чистой прибыли.",
    offerAccent: "Один класс. Общие правила.",
    offerBody:
      "Каждый NFT — договорное право на 0.25% чистой прибыли студии и read-only доступ к инвестор-дашборду. Не доля в капитале компании.",
    rights: [
      [
        "Доля прибыли",
        "0.25% квартальной чистой прибыли на NFT. Квартал без прибыли — выплата $0.",
      ],
      [
        "On-chain выплаты",
        "USDC на Solana, актуальному владельцу на снапшоте. Смарт-контракт выплат — в планах.",
      ],
      [
        "Доступ к Watchtower",
        "Статистика 4 игр, трафик, P&L и snapshots. Доступ для холдеров запланирован.",
      ],
    ],
    offerPrice: "Цена одного NFT",
    offerLimit: "Плановый лимит",
    perWallet: "NFT / кошелёк",
    offerCta: "Забрать свой из 100",
    offerTerms: "Terms of the Share",
    offerNote:
      "Рабочие условия. Продажа после публикации Terms и юридического согласования.",
    saleClosed: "ПРОДАЖА ЕЩЁ НЕ ОТКРЫТА",
    saleLive: "ПРОДАЖА ОТКРЫТА",
    walletHelp:
      "Для покупки понадобится кошелёк Solana. Изучите Terms до оплаты.",
    flowTitle: "Как будет проходить выплата",
    flow: [
      ["Отчёт студии", "Подтверждённые доходы и расходы за квартал."],
      [
        "Снапшот владельцев",
        "Первый рабочий день января, апреля, июля и октября.",
      ],
      ["Расчёт контракта", "Чистая прибыль × 25% ÷ 100."],
      ["USDC на кошелёк", "Каждая выплата — публичная транзакция."],
    ],
    flowNote:
      "Механизм запланирован; аудит и деплой контракта ещё впереди. Бизнес-календарь и сроки выплаты фиксируются в Terms.",
    mathLabel: "06 / МАТЕМАТИКА БЕЗ МАГИИ",
    mathTitle: "Всё можно пересчитать.",
    mathBody:
      "Не оценка компании. Понятная доля в потоке прибыли с прозрачным расчётом.",
    formula: "Дивиденд = (Чистая прибыль квартала × 25%) ÷ 100",
    scenarios: "ИЛЛЮСТРАЦИЯ, НЕ ОБЕЩАНИЕ",
    tableHeads: [
      "Чистая прибыль / год",
      "Пул (25%)",
      "На NFT / год",
      "На NFT / квартал",
      "% от цены / год",
    ],
    calculatorTitle: "Ваш сценарий",
    calcLabel: "Чистая прибыль студии в год",
    calcAnnual: "На один NFT в год",
    calcQuarter: "На один NFT в квартал",
    calcNote:
      "Квартальная сумма условна: предполагает равномерную прибыль в течение года. Это не прогноз и не гарантированная доходность.",
    mathNote:
      "Квартал без прибыли — дивиденд 0. Выручка и задокументированные расходы будут публиковаться в квартальном отчёте, чтобы любой холдер мог пересчитать выплату.",
    profitDefinition:
      "Чистая прибыль = подтверждённая выручка (комиссии игр, TipLink, secondary royalties, офлайн-доходы) − задокументированные расходы. Пул дивидендов не вычитается повторно: 25% считаются до распределения.",
    mathArgument:
      "При иллюстративной прибыли $400,000 в год годовой пул равен $100,000 — размеру сбора. Это сценарий, а не ожидаемый результат и не оценка студии.",
    incomeTitle: "Где будет виден мой доход?",
    incomeBody:
      "В разделе вашего NFT: снапшоты, выплаты и история. Публичные транзакции можно будет сверить в Solana-эксплорере. Функциональность выплат запланирована.",
    fundsLabel: "07 / ИСПОЛЬЗОВАНИЕ СРЕДСТВ",
    fundsTitle: "Куда идут $100,000.",
    fundsBody:
      "Конкретная работа. Проверяемые вехи. Никаких непрозрачных «прочих расходов».",
    funds: [
      [
        "Разработка",
        "Production-версии игр, токеномика, контракт дивидендов, аудит и reward-системы.",
      ],
      [
        "Интеграция реальных данных",
        "Адаптеры 4 игр, индексаторы и реальный поток событий вместо demo.",
      ],
      ["Команда", "Разработчики и дизайнер на 3–6 месяцев."],
      [
        "Масштабирование TalkChart",
        "Новые каналы, контент, Blinks и видеопроизводство.",
      ],
      ["Юрист и комплаенс", "Структура profit share, Terms и disclaimers."],
    ],
    fundTotal: "Целевой сбор",
    milestoneLabel: "ПОЭТАПНОЕ ВЫДЕЛЕНИЕ СРЕДСТВ · ПРЕДЛОЖЕНИЕ",
    milestones: [
      "При запуске дропа",
      "Mainnet игры #1 + реальные данные",
      "При первом дивиденде",
    ],
    milestoneNote:
      "Схема 50 / 30 / 20 требует подтверждения основателем и закрепления в Terms.",
    roadmapLabel: "08 / ROADMAP",
    roadmapTitle: "От инфраструктуры — к выплатам.",
    roadmapBody: "План до первого дивиденда и полной интеграции экосистемы.",
    roadmap: [
      [
        "Mainnet и открытие дропа",
        "ARES-1 в mainnet и реальные данные в Watchtower.",
        "Аудит и деплой дивидендного контракта.",
        "Открытие продажи Ecosystem Share NFT.",
      ],
      [
        "Первые выплаты",
        "Neon Relay и GUTTERCAPS в production.",
        "Первый дивиденд при наличии прибыли; январский снапшот.",
        "Инвестор-дашборд для холдеров.",
      ],
      [
        "Полная экосистема",
        "Age of Farming в production.",
        "4/4 игр с реальными данными в OS.",
        "Квартальный отчёт v2 с полной P&L-раскладкой.",
      ],
    ],
    planned: "В планах",
    roadmapNote:
      "Сроки — план, не гарантия. Первый снапшот — первый рабочий день января 2027 по календарю, который будет закреплён в Terms, не обязательно 1 января.",
    honestyLabel: "09 / СТАТУС БЕЗ ФИЛЬТРОВ",
    honestyTitle: "Что есть. Что строим. Что дальше.",
    honesty: [
      [
        "Есть сегодня",
        "Watchtower: код, read-only API, аналитика, инвестор-отчёты и snapshots.",
        "4 игры на стадиях prototype / alpha / beta.",
        "TalkChart: live-каналы SEO/GEO, X, видео, радар и TipLink.",
      ],
      [
        "В работе",
        "Mainnet-деплой ARES-1.",
        "Подключение реальных событий 4 игр к OS.",
        "Сейчас игровые данные в демо-режиме.",
      ],
      [
        "В планах",
        "Смарт-контракт дивидендов и первый платёж.",
        "4/4 игр в production и доступ холдеров.",
        "Мобильные клиенты.",
      ],
    ],
    honestyNote:
      "Мы не выдаём демо за реальные цифры. Макеты на этой странице помечены DEMO DATA; изображения игр — CONCEPT ART. Статусы продуктов приведены по брифу студии.",
    faqLabel: "10 / ВОПРОСЫ И ОТВЕТЫ",
    faqTitle: "Прежде чем принять решение.",
    faqs: [
      [
        "Что именно я покупаю?",
        "Договорное право на 0.25% чистой прибыли студии и read-only доступ к инвестор-дашборду Watchtower. Полный документ Terms будет предоставлен до оплаты. NFT не даёт доли в капитале студии.",
      ],
      [
        "Когда и как я получаю деньги?",
        "Планируются ежеквартальные выплаты USDC в сети Solana через смарт-контракт. Получатель — владелец NFT на снапшоте в первый рабочий день января, апреля, июля или октября. Контракт ещё не развёрнут; точный календарь и срок выплаты фиксируются в Terms.",
      ],
      [
        "Что происходит, когда я продаю NFT?",
        "Права переходят покупателю со следующего снапшота. Получателем выплаты является зафиксированный на снапшоте владелец.",
      ],
      [
        "А если у студии нет прибыли?",
        "Тогда дивиденд равен 0. Право на долю прибыли и доступ к дашборду сохраняются согласно Terms. Доход и ликвидность NFT не гарантированы; возможна потеря вложенных средств.",
      ],
      [
        "Почему вам можно верить?",
        "Архитектура Watchtower предусматривает quality-статусы данных и проверяемую отчётность. Выплаты планируются публичными on-chain транзакциями. Ссылки на код, аудит и контракт должны быть опубликованы до продажи. Milestone-схема 50/30/20 пока требует подтверждения — мы не выдаём её за действующий механизм.",
      ],
      [
        "Как считается чистая прибыль?",
        "Подтверждённая выручка студии минус задокументированные расходы. В выручку входят комиссии игр, TipLink, secondary royalties и подтверждённые офлайн-доходы. Дивидендный пул — 25% прибыли до распределения, без повторного вычитания.",
      ],
    ],
    finalLabel: "ПРОЗРАЧНОСТЬ НАЧИНАЕТСЯ ЗДЕСЬ",
    finalTitle: "100 долей. Один общий результат.",
    finalBody:
      "Одноразовый дроп. После закрытия mint отключается. Узнайте об открытии продажи и публикации Terms.",
    emailLabel: "Ваш email",
    emailPlaceholder: "you@example.com",
    join: "В лист ожидания",
    sending: "Отправляем…",
    formSoon:
      "Лист ожидания скоро откроется. Сейчас email не собираются и не сохраняются.",
    formConsent:
      "Отправляя email, вы соглашаетесь получить уведомление о запуске. Это не бронь NFT и не обязательство покупки.",
    formSuccess: "Вы в списке. Сообщим об открытии продажи.",
    formError: "Не удалось отправить email. Попробуйте ещё раз позже.",
    formCooldown:
      "Этот адрес отправлен только что. Повторная отправка возможна через полминуты.",
    optOut: "Отозвать согласие",
    consentSaved:
      "Согласие зафиксировано в журнале этого браузера (interlock i-02).",
    consentOptOut: "Согласие отозвано. Запись журнала обновлена.",
    formUnavailable:
      "Подписка ещё не подключена. Ваш email не отправлен и не сохранён.",
    contact: "Задать вопрос основателю",
    contactSoon: "Контакт основателя будет опубликован до продажи.",
    termsTitle: "Terms of the Share",
    termsBadge: "ДОКУМЕНТ В ПОДГОТОВКЕ",
    termsIntro:
      "Это краткое описание рабочих условий, а не полный договор. Продажа закрыта до публикации согласованных Terms.",
    termsItems: [
      "Один класс: 100 NFT по $1,000; плановый лимит — 10 на кошелёк.",
      "Один NFT: 0.25% чистой прибыли студии и read-only доступ к Watchtower.",
      "Квартальные выплаты в USDC (Solana), при отсутствии прибыли — $0.",
      "Снапшот: первый рабочий день января, апреля, июля и октября. Права переходят со следующего снапшота.",
      "Контракт, аудит, календарь, юрисдикция, юридическая квалификация и схема 50/30/20 требуют финализации.",
    ],
    termsEnd:
      "Полный текст прав будет доступен здесь до открытия продажи. Не переводите средства до его публикации.",
    termsRead: "Открыть полный документ",
    legalTitle: "ВАЖНО · ПРОЕКТ ЮРИДИЧЕСКОГО ТЕКСТА",
    legal:
      "Ecosystem Share NFT представляет собой договорное право на долю в чистой прибыли студии и доступ к инвестор-дашборду. Это не игровой токен; оно не даёт доли в капитале студии и не является индивидуальной инвестиционной рекомендацией. Юридическая квалификация, включая применимость регулирования ценных бумаг, зависит от юрисдикции и должна быть подтверждена юристом до продажи. Прошлые результаты не гарантируют будущий доход; квартал без прибыли означает нулевой дивиденд. Возможна потеря вложенных средств. Перед покупкой проконсультируйтесь с квалифицированным юристом и налоговым советником. Полные Terms предоставляются до открытия продажи. Финальные формулировки утверждаются юристом студии.",
    footerNote: "Инфраструктура доверия для Web3-игр.",
    footerRights: "Все права защищены.",
    top: "Наверх",
  },
  en: {
    metaTitle: "Games Watchtower — a transparent Web3 gaming ecosystem",
    metaDescription:
      "4 games on Solana. 1 operating system. 100 Ecosystem Share NFTs = 25% of studio net profit. Transparent math and planned quarterly USDC payouts.",
    nav: ["Ecosystem", "Watchtower", "The math", "Roadmap"],
    navCta: "Become an investor",
    menu: "Open menu",
    close: "Close",
    skip: "Skip to content",
    heroEyebrow: "GAMES WATCHTOWER × ECOSYSTEM SHARE",
    heroTitle: ["A transparent Web3", "gaming ecosystem."],
    heroAccent: "No hidden numbers.",
    heroSub: "4 games on Solana. 1 operating system.",
    heroBody:
      "100 Ecosystem Share NFTs. Together, 25% of the studio’s net profit. The same dashboard as the founder. Quarterly USDC payouts you can verify on-chain.",
    heroPrimary: "Get your share",
    heroSecondary: "See the dashboard",
    demo: "demo",
    plannedPresale: "Planned presale",
    heroNote: "Dividend smart contract is planned. The sale is not open yet.",
    onSolana: "Built on Solana",
    transparent: "Transparent by design",
    dashboard: {
      title: "Ecosystem overview",
      welcome: "The whole studio. One workspace.",
      tabs: ["Overview", "Funnels", "Investors", "Acquisition"],
      ecosystem: "Ecosystem",
      quality: "Data quality",
      events: "Event stream",
      eventNote: "Illustration, not actual activity",
      live: "READ-ONLY",
      games: "Games",
      sources: "Sources",
      profit: "Net profit",
      unavailable: "No live data",
      integration: "Integration in progress",
      coverage: "Data coverage",
      report: "Quarterly report",
      wallet: "Holder wallet",
      snapshots: "Snapshots & payouts",
      planned: "Planned",
      channels: "Acquisition channels",
      bot: "Bots and people counted separately",
      funnelStages: ["Source", "Visit", "Onboarding", "Game"],
      funnelNote: "Funnel diagram • conversions unavailable",
      investorNote: "Personal access will follow launch",
      trafficNote: "Historical data is being connected",
      os: "Studio operating system",
      preview: "Interactive mockup",
      noLive: "Live data not connected",
      expand: "Expand demo",
      collapse: "Collapse demo",
    },
    data: {
      quality: {
        complete: "COMPLETE",
        partial: "PARTIAL",
        unavailable: "UNAVAILABLE",
      },
      qualityTitle: "Data quality",
      qualityNote:
        "Hub vocabulary: complete — confirmed, partial — some fields missing, unavailable — no data.",
      source: "Source",
      asOf: "As of",
      formula: "Formula",
      timezone: "UTC",
      demo: "DEMO DATA",
      demoNote: "Values come from the hub’s mock mode and are not factual.",
      loading: "Reading data from the hub…",
      retry: "Retry request",
      showSource: "Show source",
      updated: "Data updated",
      notUpdated: "No live data received yet",
      readOnly: "READ-ONLY",
      unavailableTitle: "Data unavailable",
      mockBanner:
        "The hub is answering in mock-read-model mode. Every number on this page is demo data, not fact.",
      reasons: {
        endpoint_not_deployed:
          "The endpoint is missing from the current hub build. No values are substituted.",
        timeout: "The hub did not answer in time. Stale values are not substituted.",
        network_error: "The hub request did not complete: the network is unreachable.",
        http_error: "The hub answered with an error.",
        not_json: "The response is not JSON — data rejected.",
        unknown_endpoint: "Unknown endpoint.",
      },
    },
    hub: {
      label: "06 / ECOSYSTEM STATUS",
      title: "What is connected, and what is not.",
      body: "The status screen reads one hub endpoint and shows only what it returned. If the hub stays silent, the screen says so and assigns no levels.",
      endpoint: "Endpoint",
      navLabel: "Status",
      games: "Games",
      apps: "Services",
      stage: "Stage",
      level: "Level",
      connected: "Connected",
      disconnected: "Not connected",
      why: "Reason",
      checkedAt: "Checked",
      levelsTitle: "Maturity levels L0–L4",
      levelsNote: "The hub publishes the level vocabulary. The landing never assigns levels on its own.",
      levels: [
        ["L0", "Idea: repository and description"],
        ["L1", "Mockup: interfaces on mock data"],
        ["L2", "Integration: adapters configured, events flowing"],
        ["L3", "Live data: confirmed stream, reports reconcile"],
        ["L4", "Autonomy: alerts and regular reporting"],
      ],
      appsList: [
        ["Watchtower API", "read-only analytics"],
        ["TalkChart", "acquisition engine (interlock i-09)"],
        ["Consent & opt-out", "consent journal (interlock i-02)"],
        ["Snapshot publisher", "payout publication after confirmation"],
      ],
      appsNote: "The service list is the landing’s contract with the hub, not a readiness report.",
      pendingTitle: "The hub does not serve this endpoint yet",
      pendingBody:
        "The endpoint is missing from the current hub build, so levels L0–L4, connections and reasons are not shown. There will be no eyeballed estimates here.",
      pendingNext: "Once the endpoint ships, the screen turns on without any change on the landing.",
      schemaTitle: "Expected response schema",
      schemaNote: "The schema is pinned here so the landing and the hub mean the same thing.",
      inventoryTitle: "What is known right now",
      inventoryNote:
        "Adapter readiness comes from GET /api/read-model and is shown as is — with an unavailable quality.",
      adaptersLabel: "Adapters configured",
      retry: "Retry request",
    },
    snapshots: {
      label: "07 / PAYOUTS & SNAPSHOTS",
      navLabel: "Snapshots",
      title: "Quarters you can verify.",
      body: "Every confirmed quarter comes from the hub snapshots endpoint and carries a link to its source. Unconfirmed payouts never appear on this page.",
      formulaTitle: "Formula",
      formula: "dividend per NFT per quarter = (studio net profit for the quarter × 25%) / 100",
      formulaNote: "Rounding is always down, to the cent: a payout can never exceed the pool.",
      calendarTitle: "Snapshot calendar",
      calendar: "First business day of January, April, July and October, UTC.",
      calendarNote:
        "Exchange holidays are not modelled yet: the date-shift rule needs operator approval.",
      holderTitle: "Recipient",
      holder:
        "The current NFT holder at the moment of the snapshot. Rights transfer to a buyer from the next snapshot.",
      zeroTitle: "A quarter without profit",
      zero: "We show $0 and explain why. Zero quarters are neither hidden nor replaced with a forecast.",
      tableHead: ["Quarter", "Snapshot", "Net profit", "Pool 25%", "Per NFT", "Status", "Source"],
      statusPublished: "Published",
      statusPending: "Not published yet",
      statusZero: "No profit — the dividend is $0",
      empty: "The hub has not returned a single snapshot yet.",
      emptyWhy:
        "A snapshot is published only after operator confirmation and a frozen report — that is a rule, not a delay.",
      openSource: "Open source",
      nextTitle: "Next snapshot",
      illustrationTitle: "An illustration of the formula — not a promise",
      illustration:
        "With $200,000 of net profit for the year the pool would be $50,000 and one NFT would receive $500 for the year and $125 for the quarter.",
      illustrationNote:
        "This is the arithmetic of the formula, not a forecast or a guarantee. A quarter without profit pays $0.",
      trendTitle: "Snapshot history",
      trendEmpty: "There is no history until the first snapshot is published.",
      trendMinted: "Minted",
      trendBurned: "Burned",
      trendPlayers: "Active players",
    },
    compliance: {
      label: "08 / BOUNDARIES OF THE OFFER",
      navLabel: "Legal",
      title: "What exactly an investor buys.",
      disclaimerTitle: "Subject of the deal",
      disclaimer:
        "An Ecosystem Share NFT is a contractual right to a share of the studio’s net profit plus read-only dashboard access. It is not equity in the company, not an in-game token and not investment advice.",
      riskTitle: "Risks to accept",
      risks: [
        "The NFT may fall to zero: there may be no secondary market.",
        "A quarter without net profit means a $0 payout.",
        "The legal classification of the NFT depends on jurisdiction and is unconfirmed before the sale.",
        "The payout smart contract is not deployed and has not been audited yet.",
      ],
      kycTitle: "KYC / AML",
      kyc: "Identity verification will be required before purchase. The KYC/AML provider is not selected yet; status: awaiting an operator decision.",
      kycPending: "Awaiting an operator decision",
      jurisdictionTitle: "Jurisdiction",
      jurisdiction:
        "The list of restricted jurisdictions is published here before the sale opens. It is empty today because the legal entity and its registration are not defined yet.",
      jurisdictionPending: "Not published",
      walletTitle: "Per-wallet limit",
      wallet: "The limit is a single configuration parameter and is enforced at mint time.",
      mintTitle: "Mint program",
      mint: "The program address is not published until the operator confirms it. There will be no invented address here.",
      mintSupply: "Supply",
      mintStatus: "Status",
      mintInProgress: "In progress",
      mintAudit: "Audit",
      mintMultisig: "Multisig",
      taxTitle: "Taxes",
      tax: "The tax treatment of payouts depends on the investor’s jurisdiction. The studio does not provide tax advice.",
      termsTitle: "Terms",
      terms: "The final Terms of the Share document is published before the sale opens. Until then the sale stays closed.",
      reviewNote:
        "Legal review before a public mint is an operator decision, not an automatic pipeline step.",
      opsTitle: "Operations and resilience",
      opsText:
        "Service targets: 99.9% availability and 300 ms p95 API response. Public availability reports, content and configuration backups, an SBOM and a rollback runbook are not published yet.",
      opsPending: "Runbooks in progress",
    },
    nftLabel: "ONE NFT. A SHARE OF THE ECOSYSTEM.",
    nftProfit: "of the studio’s net profit",
    nftSupply: "Planned supply",
    nftUnits: "NFTs",
    nftAccess: "+ Watchtower access",
    stats: [
      "games in the ecosystem",
      "organic traffic channels",
      "operating system",
      "NFTs = 25% of net profit",
    ],
    statsDetail: [
      "beta / alpha / prototype",
      "SEO, GEO, X, video, radar, TipLink",
      "with a read-only API",
      "one class · one-time drop",
    ],
    statsNote:
      "No invented metrics. Interfaces on this page are demo mockups, not live data.",
    problemLabel: "01 / PROBLEM → SOLUTION",
    problemTitle: "Not “trust us.”",
    problemAccent: "Verify it yourself.",
    problemBody:
      "Web3 game investors often have nothing to verify. Screenshots instead of reports. Promises instead of numbers. Honest projects get lost among those who just promise louder.",
    problemEnd:
      "We’re building a different model: transparency as infrastructure, not a presentation.",
    problemCards: [
      ["No closed books", "The same data as the founder."],
      ["No vanity metrics", "Quality and availability for every metric."],
      [
        "No “take our word for it”",
        "A payout plan with on-chain verification.",
      ],
    ],
    watchLabel: "02 / OPERATING SYSTEM",
    watchTitle: "A source behind every number.",
    watchBody:
      "Games Watchtower is the studio’s core, open to the investor. From a game event to a quarterly report — in one system.",
    watchFeatures: [
      [
        "One event layer",
        "On-chain and off-chain: deduplication, cursors, backfill and gap detection.",
      ],
      [
        "Read-only by default",
        "Analytics, funnels, alerts and an AI analyst. No direct writes to the blockchain.",
      ],
      [
        "Verifiable reporting",
        "Investor reports, snapshots and cross-game segments.",
      ],
    ],
    watchQuote:
      "“No invented numbers” is a system principle, not a marketing slogan.",
    watchQuality: "Every metric carries a quality status and confidence:",
    watchCaption:
      "Demonstration mockup of Watchtower. Original screenshots have not been provided yet.",
    gamesLabel: "03 / GAMING ECOSYSTEM",
    gamesTitle: "Four worlds. One ecosystem.",
    gamesBody:
      "Different game loops. Shared infrastructure. A share in the entire studio, not a bet on a single game.",
    concept: "CONCEPT ART",
    gameData: "Data: integration in progress",
    games: [
      {
        name: "ARES-1",
        sub: "Potato Colony on Solana",
        stage: "beta",
        genre: "FARMING · SOLANA",
        body: "Plots, the POTATO resource and rewards. The most mature game — mainnet planned for Q4 2026.",
      },
      {
        name: "Age of Farming",
        sub: "Grow. Harvest. Create.",
        stage: "prototype",
        genre: "FARMING · CRAFTING",
        body: "Plots, harvests and crafting chains. A farming economy with balanced resource sinks and sources.",
      },
      {
        name: "Neon Relay",
        sub: "Make speed your game.",
        stage: "prototype",
        genre: "RACING · NEON DM",
        body: "Races and Neon DM — a fast competitive loop with on-chain reward settlement.",
      },
      {
        name: "GUTTERCAPS",
        sub: "Collect. Battle. Win.",
        stage: "alpha",
        genre: "COLLECTIBLES · PVP",
        body: "Collectibles, PvP wagers and the $CG token. On-chain invariants and anti-fraud built into the indexer.",
      },
    ],
    gamesNote:
      "Stages follow the studio registry in the brief. Illustrations are concept art, not gameplay screenshots.",
    trafficLabel: "04 / ACQUISITION ENGINE",
    trafficTitle: "We don’t buy audiences.",
    trafficAccent: "We find our people.",
    trafficBody:
      "TalkChart is the studio’s in-house off-chain acquisition engine. From the first search to the first action in a game.",
    channels: [
      [
        "SEO / GEO",
        "Programmatic pages for Google, Perplexity and ChatGPT Search.",
      ],
      [
        "X / Twitter",
        "Digests and interactive Solana Blinks straight in the feed.",
      ],
      ["Shorts / TikTok / Reels", "15-second vertical videos."],
      ["Whale radar", "A terminal with 1h forecasts as a retention loop."],
      ["TipLink", "Sign in with Google — no wallet or seed phrase needed."],
    ],
    trafficStats: ["campaigns", "sources", "target pages", "ad spend"],
    trafficNote:
      "Channels are live according to the studio. Historical stats are being connected to Watchtower. No visitor counts are claimed here.",
    offerLabel: "05 / ECOSYSTEM SHARE NFT",
    offerTitle: "100 NFTs. 25% of net profit.",
    offerAccent: "One class. Shared rules.",
    offerBody:
      "Each NFT is a contractual right to 0.25% of studio net profit and read-only investor dashboard access. It is not equity in the company.",
    rights: [
      [
        "Profit share",
        "0.25% of quarterly net profit per NFT. A quarter with no profit means a $0 payout.",
      ],
      [
        "On-chain payouts",
        "USDC on Solana, to the holder of record at the snapshot. Dividend smart contract is planned.",
      ],
      [
        "Watchtower access",
        "4-game stats, traffic, P&L and snapshots. Holder access is planned.",
      ],
    ],
    offerPrice: "Price per NFT",
    offerLimit: "Planned limit",
    perWallet: "NFTs / wallet",
    offerCta: "Claim yours, one of 100",
    offerTerms: "Terms of the Share",
    offerNote:
      "Working terms. Sale follows publication of Terms and legal approval.",
    saleClosed: "SALE IS NOT OPEN YET",
    saleLive: "SALE IS OPEN",
    walletHelp: "You will need a Solana wallet. Read the Terms before paying.",
    flowTitle: "How payouts will work",
    flow: [
      ["Studio report", "Verified quarterly revenue and documented expenses."],
      [
        "Holder snapshot",
        "First business day of January, April, July and October.",
      ],
      ["Contract calculation", "Net profit × 25% ÷ 100."],
      ["USDC to your wallet", "Every payout is a public transaction."],
    ],
    flowNote:
      "Planned mechanism; contract audit and deployment are ahead. Business calendar and payout timing will be fixed in the Terms.",
    mathLabel: "06 / MATH, NOT MAGIC",
    mathTitle: "You can check every number.",
    mathBody:
      "Not a company valuation. A clear share of a profit stream, transparently calculated.",
    formula: "Dividend = (Quarterly net profit × 25%) ÷ 100",
    scenarios: "ILLUSTRATION, NOT A PROMISE",
    tableHeads: [
      "Net profit / year",
      "Pool (25%)",
      "Per NFT / year",
      "Per NFT / quarter",
      "% of price / year",
    ],
    calculatorTitle: "Your scenario",
    calcLabel: "Annual studio net profit",
    calcAnnual: "Per NFT per year",
    calcQuarter: "Per NFT per quarter",
    calcNote:
      "Quarterly amounts assume evenly distributed annual profit. This is not a forecast or guaranteed return.",
    mathNote:
      "A quarter with no profit means a zero dividend. Revenue and documented expenses will be published in quarterly reports so every holder can recompute their payout.",
    profitDefinition:
      "Net profit = verified revenue (game fees, TipLink, secondary royalties, offline income) − documented expenses. The dividend pool is not deducted twice: 25% is calculated before distribution.",
    mathArgument:
      "At an illustrative $400,000 annual profit, the annual pool is $100,000 — equal to the raise. This is a scenario, not an expected result or a studio valuation.",
    incomeTitle: "Where will I see my income?",
    incomeBody:
      "In your NFT section: snapshots, payouts and history. Public transactions will be verifiable in a Solana explorer. Payout functionality is planned.",
    fundsLabel: "07 / USE OF FUNDS",
    fundsTitle: "Where the $100,000 goes.",
    fundsBody:
      "Specific work. Verifiable milestones. No opaque “miscellaneous expenses.”",
    funds: [
      [
        "Development",
        "Production games, tokenomics, dividend contract, audit and reward systems.",
      ],
      [
        "Real data integration",
        "Adapters for 4 games, indexers and a real event stream instead of demo.",
      ],
      ["Team", "Developers and a designer for 3–6 months."],
      [
        "Scaling TalkChart",
        "New channels, content, Blinks and video production.",
      ],
      ["Legal & compliance", "Profit-share structure, Terms and disclaimers."],
    ],
    fundTotal: "Target raise",
    milestoneLabel: "MILESTONE RELEASE · PROPOSED",
    milestones: [
      "At drop launch",
      "Game #1 mainnet + live data",
      "At the first dividend",
    ],
    milestoneNote:
      "The 50 / 30 / 20 structure requires founder confirmation and inclusion in the Terms.",
    roadmapLabel: "08 / ROADMAP",
    roadmapTitle: "From infrastructure to payouts.",
    roadmapBody:
      "The path to the first dividend and a fully connected ecosystem.",
    roadmap: [
      [
        "Mainnet & the drop",
        "ARES-1 mainnet and real data in Watchtower.",
        "Dividend contract audit and deployment.",
        "Ecosystem Share NFT sale opens.",
      ],
      [
        "First payouts",
        "Neon Relay and GUTTERCAPS in production.",
        "First dividend if profitable; January snapshot.",
        "Investor dashboard for holders.",
      ],
      [
        "The full ecosystem",
        "Age of Farming in production.",
        "4/4 games sending real data to the OS.",
        "Quarterly report v2 with a full P&L breakdown.",
      ],
    ],
    planned: "Planned",
    roadmapNote:
      "Target dates, not guarantees. The first snapshot is the first business day of January 2027 under the calendar to be fixed in the Terms — not necessarily January 1.",
    honestyLabel: "09 / STATUS, UNFILTERED",
    honestyTitle: "What exists. What’s next.",
    honesty: [
      [
        "Exists today",
        "Watchtower: code, read-only API, analytics, investor reports and snapshots.",
        "4 games at prototype / alpha / beta.",
        "TalkChart: live SEO/GEO, X, video, radar and TipLink channels.",
      ],
      [
        "In progress",
        "ARES-1 mainnet deployment.",
        "Connecting real events from the 4 games to the OS.",
        "Game data currently in demo mode.",
      ],
      [
        "Planned",
        "Dividend smart contract and first payout.",
        "4/4 games in production and holder access.",
        "Mobile clients.",
      ],
    ],
    honestyNote:
      "We don’t pass demo off as real numbers. Mockups here carry DEMO DATA labels; game illustrations carry CONCEPT ART labels. Product statuses are from the studio brief.",
    faqLabel: "10 / QUESTIONS & ANSWERS",
    faqTitle: "Before you make a decision.",
    faqs: [
      [
        "What exactly am I buying?",
        "A contractual right to 0.25% of studio net profit and read-only Watchtower investor dashboard access. The complete Terms document will be provided before payment. The NFT grants no equity in the studio.",
      ],
      [
        "When and how do I get paid?",
        "Quarterly USDC payouts on Solana via smart contract are planned. The recipient is the holder of record on the first business day of January, April, July or October. The contract is not deployed yet; the exact calendar and payout timing will be fixed in the Terms.",
      ],
      [
        "What happens when I sell the NFT?",
        "Rights transfer to the buyer from the next snapshot. The holder recorded at the snapshot receives the corresponding payout.",
      ],
      [
        "What if the studio makes no profit?",
        "Then the dividend is zero. Profit-share rights and dashboard access remain subject to the Terms. Income and NFT liquidity are not guaranteed; you may lose your investment.",
      ],
      [
        "Why should I trust you?",
        "Watchtower is designed around data-quality labels and verifiable reports. Payouts are planned as public on-chain transactions. Code, audit and contract links must be published before sale. The 50/30/20 milestone proposal still needs confirmation — we do not present it as an active mechanism.",
      ],
      [
        "How is net profit calculated?",
        "Verified studio revenue minus documented expenses. Revenue includes game fees, TipLink, secondary royalties and verified offline income. The dividend pool is 25% of profit before distribution, with no double deduction.",
      ],
    ],
    finalLabel: "TRANSPARENCY STARTS HERE",
    finalTitle: "100 shares. One shared outcome.",
    finalBody:
      "One-time drop. Mint disables after close. Get notified when the sale opens and the Terms are published.",
    emailLabel: "Your email",
    emailPlaceholder: "you@example.com",
    join: "Join the waitlist",
    sending: "Sending…",
    formSoon:
      "The waitlist will open soon. Emails are not being collected or stored yet.",
    formConsent:
      "By submitting your email, you agree to receive a launch notification. This is not an NFT reservation or a commitment to purchase.",
    formSuccess: "You’re on the list. We’ll let you know when the sale opens.",
    formError: "Could not submit your email. Please try again later.",
    formCooldown:
      "This address was just submitted. You can try again in half a minute.",
    optOut: "Withdraw consent",
    consentSaved:
      "Consent recorded in this browser’s journal (interlock i-02).",
    consentOptOut: "Consent withdrawn. The journal entry was updated.",
    formUnavailable:
      "Subscriptions are not connected yet. Your email was not sent or saved.",
    contact: "Ask the founder a question",
    contactSoon: "Founder contact details will be published before the sale.",
    termsTitle: "Terms of the Share",
    termsBadge: "DOCUMENT IN PREPARATION",
    termsIntro:
      "This is a summary of working terms, not the complete agreement. The sale remains closed until legally approved Terms are published.",
    termsItems: [
      "One class: 100 NFTs at $1,000; planned wallet limit of 10.",
      "One NFT: 0.25% of studio net profit and read-only Watchtower access.",
      "Quarterly USDC (Solana) payouts; no profit means $0.",
      "Snapshot: first business day of January, April, July and October. Rights transfer from the next snapshot.",
      "Contract, audit, calendar, jurisdiction, legal classification and 50/30/20 structure require finalization.",
    ],
    termsEnd:
      "Full rights will be available here before the sale opens. Do not send funds before publication.",
    termsRead: "Read the full document",
    legalTitle: "IMPORTANT · DRAFT LEGAL NOTICE",
    legal:
      "An Ecosystem Share NFT is a contractual right to a share of the studio’s net profit and access to the investor dashboard. It is not an in-game token; it grants no equity in the studio and is not individual investment advice. Legal classification, including applicable securities regulation, depends on jurisdiction and must be reviewed by counsel before sale. Past performance does not guarantee future income; a quarter with no profit means a zero dividend. You may lose your investment. Consult a qualified legal and tax professional before purchasing. Full Terms will be provided before the sale opens. Final wording is subject to approval by the studio’s counsel.",
    footerNote: "Trust infrastructure for Web3 gaming.",
    footerRights: "All rights reserved.",
    top: "Back to top",
  },
};
